/**:
  ros__parameters:
    port: /dev/neo-s300-2
    baud: 115200 #500000 transmission speed of SIKC S300 is 38400 and not 500000
    scan_cycle_time: 0.040
    scan_duration: 0.025
    scan_delay: 0.045
    frame_id: lidar_2_link

